[phases.setup]
aptPkgs = ["tesseract-ocr", "libgl1-mesa-glx", "libglib2.0-0", "python3-distutils"]

[phases.install]
cmds = ["pip install --upgrade pip setuptools", "pip install -r requirements.txt"]

[start]
cmd = "python main.py"
