[phases.setup]
aptPkgs = ["tesseract-ocr", "libgl1-mesa-dev", "libglib2.0-0", "libgomp1", "libgcc-s1", "libsm6", "libxext6", "libxrender-dev", "libfontconfig1"]

[phases.install]
cmds = [". /opt/venv/bin/activate && pip install --upgrade pip setuptools wheel", ". /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "python main.py"
