[phases.setup]
aptPkgs = ["tesseract-ocr", "libgl1-mesa-dev", "libglib2.0-0", "libgomp1", "libgcc-s1"]

[phases.install]
cmds = ["pip install --upgrade pip setuptools wheel", "pip install -r requirements.txt"]

[start]
cmd = "python main.py"
